### ISSUE TITLE
--ipfs-publish does not produce correct CID for some files

### ISSUE THREAD

**Issue by aidanok** [ArweaveTeam/arweave-deploy#16]
--ipfs-publish flag produces different CIDs than the `ipfs add` command for files above the default IPFS chunk size (256KiB)

Workaround: 

```bash
ipfs add -n --offline myfile.png
```
Will give you a CID

```bash
arweave deploy --tag "IPFS-Add:CID" myfile.png
```

Will publish the file on Arweave with the correct CID. 

You can also use https://perma-pin.bloc.space to upload new files to Arweave + IPFS.

**Comment by rosmcmahon** [comment]
This workaround should probably get implemented ☝️

**Comment by yusefnapora** [comment]
You might be interested in the [ipfs-only-hash](https://github.com/alanshaw/ipfs-only-hash) package. 

It's a small wrapper around [ipfs-unixfs-importer](https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs-importer), which has interop tests to make sure it produces the same hash as `ipfs add`.
