### ISSUE TITLE
Document usage of --host <hostname_or_ip>

### ISSUE THREAD

**Issue by LeGaryGary** [ArweaveTeam/arweave-deploy#18]
I couldn't find any documentation around this CLI option

**Comment by arweave-kyle** [comment]
Hey @LeGaryGary, by default the CLI will talk to https://arweave.net, but you can use the host option to override this. An IPv4 address also works fine in the host field too.

E.g.`arweave network-info --host host.com --protocol http --port 80`.

You can also use the `debug` flag to check the loaded values and show you the requests being made in the background, so you can verify it's working as expected.

E.g. 
```
$ arweave network-info --host arweave.dev --protocol https --port 443 --debug
Loaded config:
{
    "host": "arweave.dev",
    "protocol": "https",
    "port": "443",
    "timeout": 20000,
    "logging": true
}
Requesting: https://arweave.dev:443/info
Response:   https://arweave.dev:443/info - 200
{
    "host": "arweave.dev",
    "port": "443",
    "response": "eyJuZXR3b3JrIjoiYXJ3ZWF2ZS5OLjEiLCJ2ZXJzaW9uIjo1LCJyZWxlYXNlIjozNSwiaGVpZ2h0Ijo0MTc2MDQsImN1cnJlbnQiOiJTcmxsZ3RBTVRvS19MNlV3VzFTUmloeGtOVnR0Mnp5Ynd3bVRmbkV4VGpaaDQtUXdpcm5laGd1OVpNX0w4aHA5IiwiYmxvY2tzIjo0NDI4MTQsInBlZXJzIjo4OSwicXVldWVfbGVuZ3RoIjowLCJub2RlX3N0YXRlX2xhdGVuY3kiOjI4fQ==",
    "response_time": "375ms"
}

```

**Comment by LeGaryGary** [comment]
Thank you for this information. The purpose of this issue was to provide visibility to the lack of documentation and this issue with your response will help anyone searching for it but I think it should be explained in the README or relevant location as well 👍

**Comment by Guitlle** [comment]
I have installed the docker image for the local testnet and I was looking for this. I didn't find it in the documentation and It would be so easy to just mention it for those who need this piece of information.

**Comment by rosmcmahon** [comment]
This tool is unmaintained, and has been replaced by [arkb](https://github.com/textury/arkb#arkb).
