### ISSUE TITLE
Deprecation warnings on command

### ISSUE THREAD

**Issue by LeGaryGary** [ArweaveTeam/arweave-deploy#19]
I get the following warnings when running commands:
(node:21334) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:21334) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.

**Comment by arweave-kyle** [comment]
Hi @LeGaryGary, thanks for reporting this. Which commands do you run to prompt this, and which version of node are you running this on?

**Comment by LeGaryGary** [comment]
Node version: v8.10.0
All of the commands I have tried give the warning, here is an example command that I have been getting the warning from:
`arweave status r2jaZQRQP2d1uK9-TUaYMQF2X8T3w09_jQxW0uh_MVw`

**Comment by rosmcmahon** [comment]
[UNMAINTAINED] This tool is unmaintained, and has been replaced by [arkb](https://github.com/textury/arkb#arkb).
