### ISSUE TITLE
TX Status - TX ID starting with a hyphen causes unexpected results

### ISSUE THREAD

**Issue by LeGaryGary** [ArweaveTeam/arweave-deploy#20]
`arweave status -hvARuCZcnPxcdiqhuSx_qwVKDTsBv3aq6Inz5NiheQ` give the following:
![Screenshot from 2020-04-04 01-12-02](https://user-images.githubusercontent.com/19892506/78413863-4efdd100-7611-11ea-8e96-e99409657743.png)

**Comment by rosmcmahon** [comment]
[UNMAINTAINED] This tool is unmaintained, and has been replaced by [arkb](https://github.com/textury/arkb#arkb).
