### ISSUE TITLE
deploy --package with fonts

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/arweave-deploy#22]
It isn't clear in the docs whether or not packaged deployments support inlining custom fonts. Is this supported?

The answer should be added to the docs too 😃.

**Comment by aidanok** [comment]
Hey @CDDelta , we generally advise people to use the `deploy-dir` command to deploy projects now, which is a more reliable way of uploading a project with lots of assets. 

I believe the --package flag should package fonts, though it may depend on exactly how you include them.

**Comment by CDDelta** [comment]
Ahhh. I was deploying my app by going off the docs [here](https://docs.arweave.org/developers/tools/arweave-deploy) instead and didn't know about `deploy-dir`. I have opened a PR to update it [here](https://github.com/ArweaveTeam/docs.arweave.org-developers/pull/8)!

Thank you for your help!
