### ISSUE TITLE
Lifting 35 MB Limit on delpoy-dir

### ISSUE THREAD

**Issue by touhonoob** [ArweaveTeam/arweave-deploy#23]
Is it possible to remove the 35 MB limit on deploy-dir?

https://github.com/ArweaveTeam/arweave-deploy/blob/71c99a7bebac0e5d9c12497100453e6c309da04f/src/commands/deploy-dir.ts#L128-L130

**Comment by garrettian** [comment]
Bumping this @ldmberman

**Comment by rosmcmahon** [comment]
https://github.com/textury/arkb is the recommended tool replacing arweave-deploy.
limits have been increased to many gigabytes via the arweave-stream-tx dependency
