### ISSUE TITLE
2MB limit

### ISSUE THREAD

**Issue by wbobeirne** [ArweaveTeam/arweave-deploy#3]
Due to the lack of gzipping here, it's quite easy for a modern web-app to exceed 2mb, especially if you have any images. Is there any way around this outside of CDNing your assets and loading it that way?

**Comment by arweave-kyle** [comment]
Hey @wbobeirne, the network currently enforces a static transaction size limit so deploy mirrors this for the sake of clarity. An update is in active development at the moment to increase the transaction size limit, along with a mechanism to allow this limit to float and miners to vote on it. I expect this should be released within the next month or two so I'll leave this issue open until then.

Looking forward a bit further we're also working on features to allow multiple files to be uploaded at once, so for example uploading a dist directory with a `index.html` referencing a `style.css`, which in turn references `image.png` will be possible with each asset being turned into its own transaction under the hood. This allows for way more flexibility with regard to size limits.

Today though -- yes, simply CDNing any assets that are too large would be the way to go, and then when these features have been released the same codebase should be trivial to upload again in a way that pulls everything on-chain and removes the need for external assets.

**Comment by rosmcmahon** [comment]
This tool is unmaintained, and has been replaced by [arkb](https://github.com/textury/arkb#arkb).
