### ISSUE TITLE
Add ability to tag deployments

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/arweave-deploy#33]
It would be very powerful to be able to tag deployments made through the CLI. I need the ability to tag app deployments to query for them using GQL and prompt/redirect users to the latest version of the app on Arweave.

Not sure of how the syntax could look like. Maybe like the below:

```
arweave deploy-dir path-to/directory/to-deploy --add-tag=App-Name=GENERIC_APP
```

**Comment by samcamwilliams** [comment]
Great idea! I think we could even just use `--tag key:val`? With `:` escpable as `\:`. 

Not sure when someone on the core team. will be able to get around to this, but PRs always welcome!

**Comment by CDDelta** [comment]
I'll look into implementing this if I have the time. But perhaps Cedrik's [arkb](https://github.com/cedriking/arkb) will be a better candidate? Looks like it supersedes arweave-deploy?
