### ISSUE TITLE
Add support for ES6 feature: Optional chaining (.?)

### ISSUE THREAD

**Issue by charmful0x** [ArweaveTeam/arweave-deploy#35]
optional chaining `.?` is a recent ES6 feature. When i try to deploy a HTML file i get the following error `Unexpected token: punc (.)`

The error result is the inability to read .js file. It worked properly after removing the optional chaining operator.

i know that babel exist, but adding support for more ES6 features is helpful. Thank you

**Comment by rosmcmahon** [comment]
https://github.com/textury/arkb is the recommended tool replacing arweave-deploy

**Comment by rosmcmahon** [comment]
thanks for your issue though!
