### ISSUE TITLE
DeprecationWarning crypto.ERROR

### ISSUE THREAD

**Issue by dvncan** [ArweaveTeam/arweave-deploy#37]
When I use arweave {COMMAND} the response from the CLI is 

``` 
(node:28148) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:28148) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:28148) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead. 
```

And then CLI Command response.

I am concerned as I have not seen any reports online of this, can anyone troubleshoot the error or provide insight?

**Comment by rosmcmahon** [comment]
https://github.com/textury/arkb is now the recommended tool replacing arweave-deploy
