### ISSUE TITLE
Deploying a file without any external links causes a TypeError

### ISSUE THREAD

**Issue by zkhalapyan** [ArweaveTeam/arweave-deploy#38]
Save a file called `index.html` that's not using any external CSS files.

```
<!--index.html-->
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>
```

Now call `arweave deploy index.html --package`. 

You get an error, `TypeError: Reduce of empty array with no initial value`. 

arweave --version  is 1.9.1

**Comment by rosmcmahon** [comment]
**[UNMAINTAINED] This tool is unmaintained, and has been replaced by arkb**

https://github.com/ArweaveTeam/arweave-deploy#unmaintained-this-tool-is-unmaintained-and-has-been-replaced-by-arkb
