### ISSUE TITLE
100 file limit workaround

### ISSUE THREAD

**Issue by RickyEsclapon** [ArweaveTeam/arweave-deploy#39]
Hello, I am wondering if there's a way to get around the 100 file limit. 

I see issue #24 was about this and was closed with the following explanation:

> `arweave package` seems to help with this.

However I'm unclear on how to get it working in my case. I'm deploying a serverless Python application, and have ~200 total files across multiple folders. I'm not really sure how to use `arweave package`. 

Could someone please help? Why does there need to be a file limit in place?

**Comment by RickyEsclapon** [comment]
Also curious if there are workarounds for 10MB per file limit and 35MB per deployment one. Shouldn't we be able to upload more and be willing to pay for it?

**Comment by cedriking** [comment]
Arweave deploy has been discontinued years ago. You can use arkb now: https://github.com/textury/arkb

No file limit and no size limit using arkb.

**Comment by RickyEsclapon** [comment]
yup, thank you I had just come to that realization and was just about to close this saying just that 😅 thank you!
