### ISSUE TITLE
`arweave deploy .` gives confusing output

### ISSUE THREAD

**Issue by tmcw** [ArweaveTeam/arweave-deploy#4]
Thinking that `arweave deploy .` would deploy a directory of files, I ran it. This produced the error message

```
Detected content type: application/octet-stream
BETA NOTICE: text/* content types are currently supported, more content types will be supported in future releases.
```

So I hunted down any file that might be non-text, and removed them. Then, once the error persisted, I added a log to the CLI tool to figure out which file is triggering the message and it was… `.`. The mime-type generation / glob pattern was treating `.` as input rather than 'this directory'.

Similarly, running a command like `arweave deploy ./**/*.html` takes only one of the files (the first one, afaict).

Ideally, either globs are supported, or the behavior around inputs that users would reasonably _expect_ are globbed would be correct and clear.

**Comment by ldmberman** [comment]
Thank you for reporting the issue! Makes total sense.

**Comment by cedriking** [comment]
Issue should be solved thanks to path manifest. If it's the case please close the issue.
Release version: https://github.com/ArweaveTeam/arweave-deploy/releases/tag/v1.6.0

Thanks @tmcw
