### ISSUE TITLE
PWA manifests are not inlined correctly.

### ISSUE THREAD

**Issue by aidanok** [ArweaveTeam/arweave-deploy#6]
PWA manifests like: 

`<link rel="manifest" href="./site.webmanifest">`

are not inline correctly, it produces an empty `<style></style>` element. 

I have a standalone ts script to do this, just hacked together quickly: 

https://github.com/aokisok/permapaste/blob/4f6cefd173d6a93c1a778aa4f18c1d1b0a4e53a3/src/build/inline-manifest.ts

run with `npx ts-node inline-manifest.ts ./my/site.webmanifest  ./my/index.html`

It will insert the inlined site.webmanifest directly after the closing </title> tag in index.html. 

I do this after running `arweave package`  but before `arweave deploy`

There are other types of 'rel=XXX' which silently fail too, 'apple-touch-icon' is one, from https://realfavicongenerator.net/ .  Leaving this issue to deal with PWA manifests only. 

EDITS: updated with cleaned up version of the standalone script.

**Comment by arweave-kyle** [comment]
Hey @aokisok there's a few issues with deploying certain inline assets at the moment but this is something that will be upgraded in a release soon :)

**Comment by aidanok** [comment]
Thanks @arweave-kyle ,  I didn't look at putting in a PR for this, in a rush to submit the app! :) not sure if the inline-source lib supports this, just thought I'd put the workaround here if someone needed it. The PWA manifiest is a Json file with a specific format and icon urls inside it, which also need to be inlined for it work. 

Aswell for PWAs its impossible to inline everything, since you cannot inline service workers, browsers simply won't recognize them unless they are served separately. I know you guys have some changes in the latest releases that allow a TX to serve a path structure, so that would take care of this issue and the service worker, look forward to trying it out!

**Comment by cedriking** [comment]
Issue should be solved thanks to path manifest released on https://github.com/ArweaveTeam/arweave-deploy/releases/tag/v1.6.0

Please close if it's the case.
Thanks @aokisok !
