### ISSUE TITLE
"arweave deploy" breaks on pages with SVG images

### ISSUE THREAD

**Issue by sergejmueller** [ArweaveTeam/arweave-deploy#9]
`arweave deploy` and `arweave package` jumps out with following error on HTML files included an SVG image: 
> Error: ENOENT: no such file or directory, open '//../../.svgo.yml'

Just run the command `arweave package index.html output.html` with the simple `index.html` file, wich contains an SVG image:
```
<html>
    <body>
        <img src="https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg">
    </body>
</html>
```

#### Broken by InlineSource lib?
Not really, the same file can be compiled by pure [inline-source](https://github.com/popeindustries/inline-source) and [same options](https://github.com/ArweaveTeam/arweave-deploy/blob/1c14e7f20eaa2a737003864b744c4d1d0cf00a02/src/parsers/text-html.ts#L23-L30) without troubles.

#### The reason for the error
The error will be [returned by SVGO](https://github.com/svg/svgo/blob/10a302f73dd81122c8363ae164ba5a6af1de46e2/lib/svgo/config.js#L30). In our case the file path to the SVGO configuration cannot be resolved because Arweave compiles all dependencies into a single [arweave](https://github.com/ArweaveTeam/arweave-deploy/blob/master/dist/arweave) file.

#### Solution
I've spent a lot of time, but I could't find a solution for the problem.

**Comment by cedriking** [comment]
Thanks @sergejmueller , we are aware of the issue and we are working on an update that will solve this issue and the others related with the deploy feature 😃

**Comment by cedriking** [comment]
Hello @sergejmueller . This issue should be solved now using `deploy-dir` from path manifest, version https://github.com/ArweaveTeam/arweave-deploy/releases/tag/v1.6.0.
If you come up with a similar issue please reopen.
